# Generated by Django 2.2 on 2021-07-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_auto_20210705_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
